export interface ValorantSkin {
  id: string
  name: string
  weapon: string
  collection: string
  rarity: "Select" | "Deluxe" | "Premium" | "Ultra" | "Exclusive"
  vpPrice: number
  imageUrl: string
  releaseDate: string
}

export interface CaseType {
  id: string
  name: string
  description: string
  price: number
  type: "common" | "special" | "knife"
  image: string
  probabilities: {
    Select: number
    Deluxe: number
    Premium: number
    Ultra: number
    Exclusive: number
  }
  availableSkins: string[] // IDs das skins disponíveis nesta caixa
}

// Base de dados completa com skins reais do Valorant
export const VALORANT_SKINS: ValorantSkin[] = [
  // EXCLUSIVE (Facas e skins ultra raras) - 0.75%
  {
    id: "prime-karambit",
    name: "Prime Karambit",
    weapon: "Melee",
    collection: "Prime Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/prime-karambit.png",
    releaseDate: "2020-06-02",
  },
  {
    id: "recon-balisong",
    name: "Recon Balisong",
    weapon: "Melee",
    collection: "Recon Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/recon-balisong.png",
    releaseDate: "2021-01-12",
  },
  {
    id: "glitchpop-dagger",
    name: "Glitchpop Dagger",
    weapon: "Melee",
    collection: "Glitchpop Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/glitchpop-dagger.png",
    releaseDate: "2020-08-04",
  },
  {
    id: "elderflame-dagger",
    name: "Elderflame Dagger",
    weapon: "Melee",
    collection: "Elderflame Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/elderflame-dagger.png",
    releaseDate: "2020-07-08",
  },
  {
    id: "sovereign-sword",
    name: "Sovereign Sword",
    weapon: "Melee",
    collection: "Sovereign Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/sovereign-sword.png",
    releaseDate: "2020-09-02",
  },
  {
    id: "reaver-karambit",
    name: "Reaver Karambit",
    weapon: "Melee",
    collection: "Reaver Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/reaver-karambit.png",
    releaseDate: "2021-02-24",
  },
  {
    id: "ion-energy-sword",
    name: "Ion Energy Sword",
    weapon: "Melee",
    collection: "Ion Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/ion-energy-sword.png",
    releaseDate: "2021-03-30",
  },
  {
    id: "singularity-knife",
    name: "Singularity Knife",
    weapon: "Melee",
    collection: "Singularity Collection",
    rarity: "Exclusive",
    vpPrice: 4350,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/singularity-knife.png",
    releaseDate: "2021-07-07",
  },

  // ULTRA (Skins premium) - 10.5%
  {
    id: "prime-vandal",
    name: "Prime Vandal",
    weapon: "Vandal",
    collection: "Prime Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/prime-vandal.png",
    releaseDate: "2020-06-02",
  },
  {
    id: "elderflame-operator",
    name: "Elderflame Operator",
    weapon: "Operator",
    collection: "Elderflame Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl:
      "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/elderflame-operator.png",
    releaseDate: "2020-07-08",
  },
  {
    id: "glitchpop-phantom",
    name: "Glitchpop Phantom",
    weapon: "Phantom",
    collection: "Glitchpop Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/glitchpop-phantom.png",
    releaseDate: "2020-08-04",
  },
  {
    id: "reaver-vandal",
    name: "Reaver Vandal",
    weapon: "Vandal",
    collection: "Reaver Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/reaver-vandal.png",
    releaseDate: "2021-02-24",
  },
  {
    id: "ion-phantom",
    name: "Ion Phantom",
    weapon: "Phantom",
    collection: "Ion Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/ion-phantom.png",
    releaseDate: "2021-03-30",
  },
  {
    id: "singularity-phantom",
    name: "Singularity Phantom",
    weapon: "Phantom",
    collection: "Singularity Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl:
      "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/singularity-phantom.png",
    releaseDate: "2021-07-07",
  },
  {
    id: "oni-phantom",
    name: "Oni Phantom",
    weapon: "Phantom",
    collection: "Oni Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/oni-phantom.png",
    releaseDate: "2020-10-13",
  },
  {
    id: "dragon-vandal",
    name: "Dragon Vandal",
    weapon: "Vandal",
    collection: "Dragon Collection",
    rarity: "Ultra",
    vpPrice: 1775,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/dragon-vandal.png",
    releaseDate: "2021-01-12",
  },

  // PREMIUM (Skins de qualidade) - 20%
  {
    id: "sovereign-ghost",
    name: "Sovereign Ghost",
    weapon: "Ghost",
    collection: "Sovereign Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/sovereign-ghost.png",
    releaseDate: "2020-09-02",
  },
  {
    id: "reaver-sheriff",
    name: "Reaver Sheriff",
    weapon: "Sheriff",
    collection: "Reaver Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/reaver-sheriff.png",
    releaseDate: "2021-02-24",
  },
  {
    id: "ion-sheriff",
    name: "Ion Sheriff",
    weapon: "Sheriff",
    collection: "Ion Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/ion-sheriff.png",
    releaseDate: "2021-03-30",
  },
  {
    id: "prime-spectre",
    name: "Prime Spectre",
    weapon: "Spectre",
    collection: "Prime Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/prime-spectre.png",
    releaseDate: "2020-06-02",
  },
  {
    id: "glitchpop-judge",
    name: "Glitchpop Judge",
    weapon: "Judge",
    collection: "Glitchpop Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/glitchpop-judge.png",
    releaseDate: "2020-08-04",
  },
  {
    id: "elderflame-judge",
    name: "Elderflame Judge",
    weapon: "Judge",
    collection: "Elderflame Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/elderflame-judge.png",
    releaseDate: "2020-07-08",
  },
  {
    id: "oni-shorty",
    name: "Oni Shorty",
    weapon: "Shorty",
    collection: "Oni Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/oni-shorty.png",
    releaseDate: "2020-10-13",
  },
  {
    id: "recon-guardian",
    name: "Recon Guardian",
    weapon: "Guardian",
    collection: "Recon Collection",
    rarity: "Premium",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/recon-guardian.png",
    releaseDate: "2021-01-12",
  },

  // DELUXE (Skins intermediárias) - 35%
  {
    id: "spline-phantom",
    name: "Spline Phantom",
    weapon: "Phantom",
    collection: "Spline Collection",
    rarity: "Deluxe",
    vpPrice: 1275,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/spline-phantom.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "nebula-guardian",
    name: "Nebula Guardian",
    weapon: "Guardian",
    collection: "Nebula Collection",
    rarity: "Deluxe",
    vpPrice: 1275,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/nebula-guardian.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "sakura-vandal",
    name: "Sakura Vandal",
    weapon: "Vandal",
    collection: "Sakura Collection",
    rarity: "Deluxe",
    vpPrice: 1275,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/sakura-vandal.png",
    releaseDate: "2021-04-27",
  },
  {
    id: "forsaken-operator",
    name: "Forsaken Operator",
    weapon: "Operator",
    collection: "Forsaken Collection",
    rarity: "Deluxe",
    vpPrice: 1275,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/forsaken-operator.png",
    releaseDate: "2020-10-27",
  },
  {
    id: "magepunk-spectre",
    name: "Magepunk Spectre",
    weapon: "Spectre",
    collection: "Magepunk Collection",
    rarity: "Deluxe",
    vpPrice: 1275,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/magepunk-spectre.png",
    releaseDate: "2020-12-08",
  },
  {
    id: "wasteland-vandal",
    name: "Wasteland Vandal",
    weapon: "Vandal",
    collection: "Wasteland Collection",
    rarity: "Deluxe",
    vpPrice: 1275,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/wasteland-vandal.png",
    releaseDate: "2020-05-12",
  },

  // SELECT (Skins básicas) - 33.75%
  {
    id: "avalanche-spectre",
    name: "Avalanche Spectre",
    weapon: "Spectre",
    collection: "Avalanche Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/avalanche-spectre.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "convex-vandal",
    name: "Convex Vandal",
    weapon: "Vandal",
    collection: "Convex Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/convex-vandal.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "dot-exe-vandal",
    name: "Dot EXE Vandal",
    weapon: "Vandal",
    collection: "Dot EXE Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/dot-exe-vandal.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "smite-classic",
    name: "Smite Classic",
    weapon: "Classic",
    collection: "Smite Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/smite-classic.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "surge-spectre",
    name: "Surge Spectre",
    weapon: "Spectre",
    collection: "Surge Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/surge-spectre.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "luxe-classic",
    name: "Luxe Classic",
    weapon: "Classic",
    collection: "Luxe Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/luxe-classic.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "rush-frenzy",
    name: "Rush Frenzy",
    weapon: "Frenzy",
    collection: "Rush Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/rush-frenzy.png",
    releaseDate: "2020-04-07",
  },
  {
    id: "infantry-spectre",
    name: "Infantry Spectre",
    weapon: "Spectre",
    collection: "Infantry Collection",
    rarity: "Select",
    vpPrice: 875,
    imageUrl: "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8b1b1b1b1b1b1b1b/infantry-spectre.png",
    releaseDate: "2020-04-07",
  },
]

// 10 tipos de caixas diferentes
export const CASE_TYPES: CaseType[] = [
  // 5 CAIXAS COMUNS (R$ 3-10)
  {
    id: "starter-case",
    name: "Caixa Iniciante",
    description: "Perfeita para começar sua coleção! Skins básicas e intermediárias.",
    price: 3.0,
    type: "common",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 60, Deluxe: 35, Premium: 5, Ultra: 0, Exclusive: 0 },
    availableSkins: [
      "avalanche-spectre",
      "convex-vandal",
      "dot-exe-vandal",
      "smite-classic",
      "surge-spectre",
      "luxe-classic",
      "rush-frenzy",
      "infantry-spectre",
      "spline-phantom",
      "nebula-guardian",
      "sakura-vandal",
    ],
  },
  {
    id: "classic-case",
    name: "Caixa Clássica",
    description: "Mix equilibrado de skins Select e Deluxe com chance de Premium.",
    price: 5.0,
    type: "common",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 45, Deluxe: 40, Premium: 15, Ultra: 0, Exclusive: 0 },
    availableSkins: [
      "avalanche-spectre",
      "convex-vandal",
      "spline-phantom",
      "nebula-guardian",
      "sakura-vandal",
      "forsaken-operator",
      "magepunk-spectre",
      "sovereign-ghost",
      "recon-guardian",
      "luxe-classic",
    ],
  },
  {
    id: "standard-case",
    name: "Caixa Padrão",
    description: "Boa chance de skins Deluxe e Premium com possibilidade de Ultra.",
    price: 7.0,
    type: "common",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 30, Deluxe: 45, Premium: 20, Ultra: 5, Exclusive: 0 },
    availableSkins: [
      "spline-phantom",
      "nebula-guardian",
      "sakura-vandal",
      "forsaken-operator",
      "magepunk-spectre",
      "wasteland-vandal",
      "sovereign-ghost",
      "reaver-sheriff",
      "ion-sheriff",
      "prime-spectre",
      "prime-vandal",
    ],
  },
  {
    id: "advanced-case",
    name: "Caixa Avançada",
    description: "Foco em skins Premium e Deluxe com boa chance de Ultra.",
    price: 8.5,
    type: "common",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 20, Deluxe: 40, Premium: 30, Ultra: 10, Exclusive: 0 },
    availableSkins: [
      "forsaken-operator",
      "magepunk-spectre",
      "wasteland-vandal",
      "sovereign-ghost",
      "reaver-sheriff",
      "ion-sheriff",
      "prime-spectre",
      "glitchpop-judge",
      "elderflame-judge",
      "prime-vandal",
      "elderflame-operator",
    ],
  },
  {
    id: "premium-case",
    name: "Caixa Premium",
    description: "Skins de alta qualidade com excelente chance de Ultra.",
    price: 10.0,
    type: "common",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 15, Deluxe: 30, Premium: 40, Ultra: 15, Exclusive: 0 },
    availableSkins: [
      "sovereign-ghost",
      "reaver-sheriff",
      "ion-sheriff",
      "prime-spectre",
      "glitchpop-judge",
      "elderflame-judge",
      "oni-shorty",
      "recon-guardian",
      "prime-vandal",
      "elderflame-operator",
      "glitchpop-phantom",
      "reaver-vandal",
    ],
  },

  // 3 CAIXAS ESPECIAIS (R$ 25-40) - Skins especiais e facas
  {
    id: "elite-case",
    name: "Caixa Elite",
    description: "Skins Ultra premium com chance de conseguir facas exclusivas!",
    price: 25.0,
    type: "special",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 0, Deluxe: 15, Premium: 50, Ultra: 30, Exclusive: 5 },
    availableSkins: [
      "sovereign-ghost",
      "reaver-sheriff",
      "ion-sheriff",
      "prime-spectre",
      "glitchpop-judge",
      "elderflame-judge",
      "prime-vandal",
      "elderflame-operator",
      "glitchpop-phantom",
      "reaver-vandal",
      "ion-phantom",
      "singularity-phantom",
      "oni-phantom",
      "dragon-vandal",
      "prime-karambit",
      "glitchpop-dagger",
    ],
  },
  {
    id: "legendary-case",
    name: "Caixa Lendária",
    description: "As melhores skins do jogo com alta chance de facas!",
    price: 35.0,
    type: "special",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 0, Deluxe: 5, Premium: 35, Ultra: 50, Exclusive: 10 },
    availableSkins: [
      "prime-spectre",
      "glitchpop-judge",
      "elderflame-judge",
      "oni-shorty",
      "prime-vandal",
      "elderflame-operator",
      "glitchpop-phantom",
      "reaver-vandal",
      "ion-phantom",
      "singularity-phantom",
      "oni-phantom",
      "dragon-vandal",
      "prime-karambit",
      "recon-balisong",
      "glitchpop-dagger",
      "elderflame-dagger",
    ],
  },
  {
    id: "ultimate-case",
    name: "Caixa Suprema",
    description: "O máximo em qualidade! Apenas skins Ultra e Exclusive.",
    price: 40.0,
    type: "special",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 0, Deluxe: 0, Premium: 20, Ultra: 65, Exclusive: 15 },
    availableSkins: [
      "prime-vandal",
      "elderflame-operator",
      "glitchpop-phantom",
      "reaver-vandal",
      "ion-phantom",
      "singularity-phantom",
      "oni-phantom",
      "dragon-vandal",
      "prime-karambit",
      "recon-balisong",
      "glitchpop-dagger",
      "elderflame-dagger",
      "sovereign-sword",
      "reaver-karambit",
      "ion-energy-sword",
      "singularity-knife",
    ],
  },

  // 2 CAIXAS APENAS DE FACA (R$ 90-120)
  {
    id: "knife-collection",
    name: "Coleção de Facas",
    description: "100% garantido de conseguir uma faca! Todas as facas disponíveis.",
    price: 90.0,
    type: "knife",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 0, Deluxe: 0, Premium: 0, Ultra: 0, Exclusive: 100 },
    availableSkins: [
      "prime-karambit",
      "recon-balisong",
      "glitchpop-dagger",
      "elderflame-dagger",
      "sovereign-sword",
      "reaver-karambit",
      "ion-energy-sword",
      "singularity-knife",
    ],
  },
  {
    id: "exclusive-knife",
    name: "Facas Exclusivas",
    description: "As facas mais raras e desejadas do Valorant! 100% faca garantida.",
    price: 120.0,
    type: "knife",
    image: "/placeholder.svg?height=200&width=200",
    probabilities: { Select: 0, Deluxe: 0, Premium: 0, Ultra: 0, Exclusive: 100 },
    availableSkins: [
      "prime-karambit",
      "recon-balisong",
      "glitchpop-dagger",
      "elderflame-dagger",
      "sovereign-sword",
      "reaver-karambit",
      "ion-energy-sword",
      "singularity-knife",
    ],
  },
]

export function getSkinsByRarity(rarity: string): ValorantSkin[] {
  return VALORANT_SKINS.filter((skin) => skin.rarity === rarity)
}

export function getSkinById(id: string): ValorantSkin | undefined {
  return VALORANT_SKINS.find((skin) => skin.id === id)
}

export function getCaseById(id: string): CaseType | undefined {
  return CASE_TYPES.find((caseType) => caseType.id === id)
}

export function getSkinsForCase(caseId: string): ValorantSkin[] {
  const caseType = getCaseById(caseId)
  if (!caseType) return []

  return caseType.availableSkins
    .map((skinId) => getSkinById(skinId))
    .filter((skin): skin is ValorantSkin => skin !== undefined)
}
